### ISSUE TITLE
Is this crate released on crates.io ?

### ISSUE THREAD

**Issue by robinhundt** [ZenGo-X/rust-paillier#13]
Hello, just a quick question: 
Is this fork released on crates.io? On first glance it seems to be maintained, in contrast to the repository it was forked from, but `paillier = 2.0` seems to be the original implementation on crates.io (https://crates.io/crates/paillier).  
I'm aware that it is possible add git dependencies, but if there was a crates.io version and I just couldn't find that, I would prefer that :)

**Comment by omershlo** [comment]
Hi @robinhundt ! Thanks for the question. 
this repo is indeed maintained but not on crates.io  . originally this was to avoid confusion with the original repo and because one of its dependencies (curv) was not on crates.io ( this is a requirement) . Now that curv is taken from crates I think we can publish a version of rust paillier under a distinct different package name. 
can you please open up an issue for that ? 
cc: @survived , @elichai , let me know if I am missing something

**Comment by survived** [comment]
@omershlo right, nothing holds us from publishing this crate. Which name of the crate we should choose? Just `kzen-paillier` or something else?

**Comment by omershlo** [comment]
`kzen-paillier` will be compatible with the other crates. sounds good to me

**Comment by robinhundt** [comment]
Thanks for the fast replies! :blush: As suggested I've opened a new issues #15 :)

**Comment by survived** [comment]
Released just now as mentioned in #15 ;)
